name: ci
on:
  release:
    types: [released]
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - shell: bash
        run: |
          npm install -g pnpm
          pnpm install
          pnpm eslint .
          pnpm prettier --check .
  deploy:
    runs-on: ubuntu-latest
    needs: check-format
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - shell: bash
        env:
          USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
          mkdir -p ~/.ssh/
          touch ~/.ssh/known_hosts
          ssh-keyscan simonkurz.de >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "$SSH_KEY"
          rsync -e "ssh" --delete -av build/ $USER@simonkurz.de:$TARGET_DIR/
